spring:
  application:
    name: movie
#database connection
  datasource:
    url: jdbc:sqlserver://35.229.243.78:1433;database=test1;trustServerCertificate=true;encrypt=true
    password: p@ssw0rd
    username: sqlserver

#    url: jdbc:sqlserver://localhost:1433;database=test1;trustServerCertificate=true;encrypt=true
#    password: p@ssw0rd
#    username: sa
#    url: jdbc:sqlserver://35.201.209.200:1433;database=test1;trustServerCertificate=true;encrypt=true
#    password: p@ssw0rd
#    username: sqlserver

  jpa:
    properties:
      hibernate:
        jdbc:
        dialect: org.hibernate.dialect.SQLServerDialect
        format-sql: true
    hibernate:
      jdbc:
        batch_size: 500
        batch_versioned_data: true
      order_inserts: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    show-sql: false
  output:
    ansi:
      enabled: always
server:
  port: 8080
logging:
  config: classpath:logback-spring.xml
  level:
    root: INFO
jwt:
  token:
    expire: 10000
# email SMTP 服务器配置
mail:
  smtp:
    host: smtp.gmail.com
    port: 587
    username: ispanmove@gmail.com
    password: czdn gmwi vvtn onrx
    tls: true
front:
  url: https://starburst-cinema.xyz

paypal:
  client:
    id: AUZKqkSWZy4k4EvNxqrDsRnXcxYEY58BJVewwckiRd7ESLGh6b9OHlTK1izn_y3oka_Ey3Ic3p1ygPoU
    secret: ECcSI5sbHlTM2V6b_K83_EU0Sn5P2qy5EpVbzDzIhVCeasY7GppEhQ_zBqttuzSSsBtbU_bG2a0TT73E
  mode: sandbox

