spring:
  application:
    name: movie
#database connection
  datasource:
    url: jdbc:sqlserver://localhost:1433;database=test1;trustServerCertificate=true;encrypt=true

    password: p@ssw0rd

    username: sa
  jpa:
    properties:
      hibernate:
        jdbc:
        dialect: org.hibernate.dialect.SQLServerDialect
        format-sql: true
    hibernate:
      jdbc:
        batch_size: 500
        batch_versioned_data: true
      order_inserts: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    show-sql: true
  output:
    ansi:
      enabled: always
  profiles:
    active: '@production@'
server:
  port: 8080
logging:
  config: classpath:logback-spring.xml
  level:
    root: INFO


jwt:
  token:
    expire: 100
    
# email SMTP 服务器配置

mail:
  smtp:
    host: smtp.gmail.com
    port: 587
    username: ispanmove@gmail.com
    password: czdn gmwi vvtn onrx
    tls: true
    
front:
  url: http://localhost:5173