spring:
  application:
    name: movie
#database connection
  datasource:
    url: jdbc:sqlserver://localhost:1433;database=test1;trustServerCertificate=true;encrypt=true
    password: p@ssw0rd
    username: sa
  jpa:
    properties:
      hibernate:
        jdbc:
        dialect: org.hibernate.dialect.SQLServerDialect
        format-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    show-sql: false
  output:
    ansi:
      enabled: always
server:
  port: 8082
logging:
  config: classpath:logback-spring.xml
  level:
    root: INFO
paypal:
  client:
    id: AUZKqkSWZy4k4EvNxqrDsRnXcxYEY58BJVewwckiRd7ESLGh6b9OHlTK1izn_y3oka_Ey3Ic3p1ygPoU
    secret: ECcSI5sbHlTM2V6b_K83_EU0Sn5P2qy5EpVbzDzIhVCeasY7GppEhQ_zBqttuzSSsBtbU_bG2a0TT73E
  mode: sandbox
jwt:
  token:
    expire: 100

