spring:
  application:
    name: movie
#database connection
  datasource:
    url: jdbc:sqlserver://localhost:1433;database=test1;trustServerCertificate=true;encrypt=true
    password: sa123456
    username: sa
  jpa:
    properties:
      hibernate:
        jdbc:
        dialect: org.hibernate.dialect.SQLServerDialect
        format-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    show-sql: true
  output:
    ansi:
      enabled: always
server:
  port: 8080
logging:
  config: classpath:logback-spring.xml
  level:
    root: INFO


