spring:
  application:
    name: movie
#database connection
  datasource:
    url: jdbc:sqlserver://10.113.0.3:1433;database=test1;trustServerCertificate=true;encrypt=true
    password: u7u4vrhur12fmjujfubctji8eflv4usn
    username: sqlserver
  jpa:
    properties:
      hibernate:
        jdbc:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    show-sql: true
  output:
    ansi:
      enabled: always
server:
  port: 8080
logging:
  config: classpath:logback-spring.xml
  level:
    root: INFO
jwt:
  token:
    expire: 100
    
# email SMTP 服务器配置

mail:
  smtp:
    host: smtp.gmail.com
    port: 587
    username: ispanmove@gmail.com
    password: czdn gmwi vvtn onrx
    tls: true

